---
# Install tripleo-operator in current user environment
# and provide plugins and roles to local ansible env.
- name: Ensure there are credentials for accessing registry
  tags:
    - always
    - lab
  ansible.builtin.assert:
    that:
      - registers is defined
      - (registers|length) > 0
      - registers.0.name is defined
      - registers.0.username is defined
      - registers.0.password is defined
    msg: "It is expected to have defined at least one registry"

- name: Ensure we have ~/.ansible
  tags:
    - always
    - lab
  ansible.builtin.file:
    mode: '755'
    path: ~/.ansible
    state: directory

- name: Clone tripleo-operator-ansible
  register: git_operator
  tags:
    - always
    - lab
  ansible.builtin.git:
    dest: ~/.ansible/tripleo-operator-ansible
    repo: https://opendev.org/openstack/tripleo-operator-ansible
    update: "{{ update_operator | bool }}"
    # Upstream repo has been retired, this is the latest commit
    version: e1abb34ef8eddaebaee63012730b5c65ca731c24

- name: Build operator collection # noqa no-handler no-changed-when
  tags: always
  when: git_operator is changed
  ansible.builtin.command: "ansible-galaxy collection build --force --output-path /tmp/collections"
  register: collection_name
  args:
    chdir: ~/.ansible/tripleo-operator-ansible

- name: Install operator collection # noqa no-handler no-changed-when
  tags: always
  when: git_operator is changed
  ansible.builtin.command: "ansible-galaxy collection install --force {{ collection_name.stdout.split(' ')[-1] }}"
  args:
    chdir: ~/.ansible/tripleo-operator-ansible
