- hosts: localhost
  connection: local
  vars:
    update_operator: true
    update_rhsm: true
  name: Deploy local requirements
  roles:
    - operators
    - rhsm
- hosts: localhost
  connection: local
  become: true
  name: Install dependencies for other playbooks
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - python3-jmespath
          - python3-netaddr
        state: installed
